# Combining Samples

In [2]:
import pandas as pd
df1=pd.read_csv('./Data/Acir_mT19_allSamples_geneAbundance_tpm.txt',sep='\t').set_index('geneID')
modified_list = [item[:-2] for item in list(df1.columns)]
df1.columns=modified_list
result_df = df1.groupby(level=0, axis=1).sum()
result_df1=result_df.reset_index().set_index('geneID')
result_df1

,Acir.mT19_11-3-1,Acir.mT19_11-3-2,Acir.mT19_11-3-3,Acir.mT19_12-4-1,Acir.mT19_12-4-2,Acir.mT19_12-4-3,Acir.mT19_6-15-1,Acir.mT19_6-15-2,Acir.mT19_6-15-3,Acir.mT19_7-23-1,Acir.mT19_7-23-2,Acir.mT19_7-23-3,Acir.mT19_9-10-1,Acir.mT19_9-10-2,Acir.mT19_9-10-3,Acir.mT19_9-29-1,Acir.mT19_9-29-2,Acir.mT19_9-29-3
geneID,,,,,,,,,,,,,,,,,,
ACIR310F_RS26605_tcmP,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0
ACIR310F_RS0108495_ACIR310F_RS0108495,319.97,0.0,286.90,0.00,47.91,115.48,0.00,14.66,0.00,0.00,35.62,26.65,22.44,0.0,0.0,0.0,503.92,0.0
ACIR310F_RS0107930_ACIR310F_RS0107930,0.00,0.0,6.87,0.00,3.71,33.07,0.00,0.00,0.00,0.00,17.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0
ACIR310F_RS0108705_ACIR310F_RS0108705,0.00,0.0,161.38,0.00,328.37,344.44,158.56,378.16,257.68,0.00,266.76,51.43,134.25,0.0,0.0,0.0,0.00,0.0
ACIR310F_RS0111945_ACIR310F_RS0111945,0.00,0.0,27.15,0.00,38.33,50.94,66.41,0.00,14.11,0.00,15.70,12.40,40.43,0.0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACIR310F_RS0104440_ACIR310F_RS0104440,0.00,0.0,0.00,0.00,6.42,0.00,0.00,0.00,0.00,0.00,6.77,0.00,0.00,0.0,0.0,0.0,0.00,0.0
ACIR310F_RS0120490_murB,0.00,0.0,66.09,0.00,87.70,110.77,0.00,0.00,57.42,0.00,97.16,0.00,88.82,0.0,0.0,0.0,0.00,0.0
ACIR310F_RS0108175_ACIR310F_RS0108175,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0
ACIR310F_RS0105215_cysH,835.92,142.0,199.85,177.85,547.55,722.23,188.31,0.00,0.00,2268.39,60.09,222.89,667.51,587.8,0.0,0.0,0.00,0.0
ACIR310F_RS0100060_ACIR310F_RS0100060,0.00,0.0,2.06,0.00,6.65,6.87,0.00,0.00,0.00,0.00,0.70,29.77,8.06,0.0,0.0,0.0,0.00,0.0

In [3]:
df2=pd.read_csv('./Data/Mar_mT19_allSamples_geneAbundance_tpm.txt',sep='\t').set_index('geneID')
modified_list = [item[:-2] for item in list(df2.columns)]
df2.columns=modified_list
result_df = df2.groupby(level=0, axis=1).sum()
result_df2=result_df.reset_index().set_index('geneID')
result_df2

,mT19_11-3-1,mT19_11-3-2,mT19_11-3-3,mT19_12-4-1,mT19_12-4-2,mT19_12-4-3,mT19_6-15-1,mT19_6-15-2,mT19_6-15-3,mT19_7-23-1,mT19_7-23-2,mT19_7-23-3,mT19_9-10-1,mT19_9-10-2,mT19_9-10-3,mT19_9-29-1,mT19_9-29-2,mT19_9-29-3
geneID,,,,,,,,,,,,,,,,,,
O53_3431_O53_3431,410.48,298.08,388.81,214.37,205.82,220.19,402.49,374.17,172.99,192.95,149.26,132.69,303.96,120.40,184.72,163.24,125.88,168.40
O53_1419_O53_1419,25.74,24.10,25.38,59.49,41.99,58.38,45.16,44.65,29.00,17.71,11.17,12.84,17.62,22.08,25.71,24.11,31.15,39.83
O53_387_uvrB,10.73,11.97,12.33,17.91,8.68,10.31,10.25,9.00,10.11,2.93,5.27,4.66,6.84,5.08,7.67,4.79,3.45,5.02
O53_2898_O53_2898,12.14,6.19,11.16,16.15,12.62,26.05,15.56,14.62,10.21,4.78,2.81,2.99,2.88,2.53,4.86,1.35,1.79,3.56
O53_1175_mdnC,22.85,23.05,40.86,9.29,7.93,10.21,34.20,51.05,43.81,12.76,9.81,20.70,18.60,25.35,20.88,14.72,25.54,35.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
O53_5112_rlpA,473.38,986.02,686.00,289.39,572.55,421.19,255.83,184.04,301.40,380.91,378.70,379.74,278.25,324.70,309.48,353.44,545.66,548.46
O53_1020_psaE,3164.94,3851.53,3680.13,3022.58,1569.90,1656.46,9744.05,8949.23,5332.96,6549.78,5724.51,5228.96,5619.73,2465.40,2439.74,1703.88,2064.63,4085.29
O53_1194_O53_1194,1648.63,1415.59,1267.82,1322.14,1907.16,1931.05,1272.72,1382.79,2667.78,642.21,650.60,979.45,753.88,692.84,711.03,580.63,607.74,1316.07
O53_4358_tnpA,1240.18,892.13,745.24,2183.59,564.58,364.70,411.25,196.28,136.94,630.90,495.57,848.73,1506.01,928.78,1325.20,1219.63,881.55,380.24
O53_1466_O53_1466,38.62,24.58,35.97,28.33,20.21,18.28,14.65,18.25,14.01,12.46,7.39,10.78,13.38,8.34,10.91,5.25,6.45,8.65

In [3]:
#result_df1.to_csv('Acir_mT19_allSamples_geneAbundance_processed.csv')
#result_df2.to_csv('Mar_mT19_allSamples_geneAbundance_processed.csv')

# Geneid modification

In [4]:
import pandas as pd
Taihu98_gene_expression=pd.read_csv('./Data/Taihu98_gene_expression.csv').set_index('Unnamed: 0').rename_axis(None)
Taihu98_gene_expression.index=Taihu98_gene_expression.index.str.split('_').str[:2].str.join('_')
Taihu98_gene_expression#.to_csv('Taihu98_gene_expression_geneid_modified.csv')
Taihu98_snp=pd.read_csv('./Data/Taihu98_snp.csv').set_index('Unnamed: 0').rename_axis(None)
Taihu98_snp.index=Taihu98_snp.index.str.split('_').str[:2].str.join('_')
Taihu98_snp#.to_csv('Taihu98_snp_geneid_modified.csv')

,mG11.3.1,mG11.3.2,mG11.3.3,mG12.4.1,mG12.4.2,mG12.4.3,mG6.15.1,mG6.15.2,mG6.15.3,mG7.23.1,mG7.23.2,mG7.23.3,mG9.10.1,mG9.10.2,mG9.10.3,mG9.29.1,mG9.29.2,mG9.29.3
O53_1939,31,29,30,26,26,13,9,2,5,23,20,31,37,30,36,37,34,19
O53_3443,5,5,3,0,0,0,0,0,0,0,1,0,8,2,1,5,1,0
O53_4453,51,40,38,39,38,42,34,26,32,40,47,43,46,51,48,48,48,29
O53_47,2,0,0,0,0,0,0,0,0,0,0,0,2,1,1,5,1,0
O53_108,20,21,21,3,19,5,6,13,3,13,11,23,19,28,10,21,12,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
O53_3980,3,1,3,2,3,3,3,3,0,3,3,3,3,3,3,3,2,3
O53_1268,20,26,23,24,4,2,5,0,0,24,22,24,36,30,27,36,30,1
O53_3766,37,48,51,53,35,32,34,34,30,45,45,47,60,51,57,55,55,35
O53_2343,32,34,35,14,21,20,6,6,9,32,24,33,53,42,36,55,35,11
O53_562,3,3,5,3,3,3,1,2,0,3,4,5,3,3,4,1,9,3

In [5]:
Acir_gene_expression=pd.read_csv('./Data/Acir_gene_expression.csv').set_index('Unnamed: 0').rename_axis(None)
Acir_gene_expression.index=Acir_gene_expression.index.str.split('_').str[:2].str.join('_')
Acir_gene_expression#.to_csv('Acir_gene_expression_geneid_modified.csv')
Acir_snp=pd.read_csv('./Data/Acir_snp.csv').set_index('Unnamed: 0').rename_axis(None)
Acir_snp=Acir_snp.apply(pd.to_numeric, errors='coerce').fillna(0).astype('int64')
Acir_snp.index=Acir_snp.index.str.split('_').str[:2].str.join('_')
Acir_snp#.to_csv('Acir_snp_geneid_modified.csv')

,mG11.3.1,mG11.3.2,mG11.3.3,mG12.4.1,mG12.4.2,mG12.4.3,mG6.15.1,mG6.15.2,mG6.15.3,mG7.23.1,mG7.23.2,mG7.23.3,mG9.10.1,mG9.10.2,mG9.10.3,mG9.29.1,mG9.29.2,mG9.29.3
ACIR310F_RS0107675,0,0,0,0,1,1,0,0,0,4,4,1,0,0,0,0,0,0
ACIR310F_RS0108135,0,0,0,0,0,3,0,0,0,4,15,7,0,0,0,0,0,0
ACIR310F_RS0106860,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ACIR310F_RS0110035,0,0,0,0,4,4,0,0,0,2,9,0,0,0,0,0,0,0
ACIR310F_RS0108995,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACIR310F_RS0110170,0,0,0,0,13,8,0,0,0,11,10,1,0,0,0,0,0,0
ACIR310F_RS21225,0,0,0,0,8,2,0,0,0,2,20,3,0,0,0,0,0,0
ACIR310F_RS0114280,0,0,0,0,0,0,0,2,0,0,13,13,0,0,0,0,0,0
ACIR310F_RS0104405,0,0,0,0,6,11,0,0,0,5,23,5,0,0,0,0,0,0
ACIR310F_RS0110150,0,0,11,3,27,41,1,8,0,37,19,18,0,5,0,0,0,0

# Data Checking

In [7]:
Taihu98_snp.sum()

mG11.3.1    126167
mG11.3.2    127334
mG11.3.3    128243
mG12.4.1    122985
mG12.4.2     81672
mG12.4.3     69878
mG6.15.1     73925
mG6.15.2     57930
mG6.15.3     45021
mG7.23.1    123411
mG7.23.2    122688
mG7.23.3    126962
mG9.10.1    168536
mG9.10.2    144457
mG9.10.3    151494
mG9.29.1    153163
mG9.29.2    140860
mG9.29.3     67586
dtype: int64